version: '3'
services:
  postgres:
    image: "postgres:9.6"
    container_name: 'sshmanagerdb'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ~/sshmanager/pg:/var/lib/postgresql/data
    tty: true
    restart: always
    
  web:
    image: "gradeup/ssh-manager:0.8"
    container_name: 'sshmanager'
    ports:
      - "8000:8000"
    volumes:
      - ~/sshmanager/.env:/ssh-manager/.env
      - ~/.ssh/id_rsa.pub:/ssh-manager/id_rsa.pub
      - ~/.ssh/id_rsa:/ssh-manager/id_rsa
    tty: true
    restart: always