on:
  push:
    tags:
      - '*'

jobs:
  deploy_by_release:
    name: Release Branch Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: photon/app
          GITHUB_TOKEN:  ${{ secrets.TOKEN_GIT }}
        run: |
          docker build -t "gradeup/ssh-manager:${{ github.ref_name }}" --build-arg="GITHUB_TOKEN=${{ secrets.TOKEN_GIT }}" .
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push "gradeup/ssh-manager:${{ github.ref_name }}"